include: package:very_good_analysis/analysis_options.5.0.0.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/gen/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.config.dart

linter:
  rules:
    public_member_api_docs: false
    avoid_unused_constructor_parameters: false
