analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  extends:
    - package:dart_code_metrics/presets/all.yaml
  anti-patterns:
    - long-method
    - long-parameter-list
