name: adblocker_webview
description: A webview for flutter with adblocking capability. It's currently based on Flutter InAppWebview Plugin.
repository: https://github.com/islamdidarmd/flutter_adblocker_webview
issue_tracker: https://github.com/islamdidarmd/flutter_adblocker_webview/issues
version: 2.0.0-beta
homepage: https://github.com/islamdidarmd/flutter_adblocker_webview

environment:
  sdk: ^3.7.0

workspace:
  - packages/adblocker_core
  - packages/adblocker_manager

dependencies:
  adblocker_manager: ^1.0.0
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  very_good_analysis: ^5.1.0
