name: adblocker_webview
description: A webview for flutter with adblocking capability. It's currently based on Flutter InAppWebview Plugin.
repository: https://github.com/islamdidarmd/flutter_adblocker_webview
issue_tracker: https://github.com/islamdidarmd/flutter_adblocker_webview/issues
version: 1.0.0
homepage: https://github.com/islamdidarmd/flutter_adblocker_webview

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  http: ^0.13.5
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
