name: adblocker_webview
description: A webview for flutter with adblocking capability. It's currently based on Flutter InAppWebview Plugin.
repository: https://github.com/islamdidarmd/flutter_adblocker_webview
issue_tracker: https://github.com/islamdidarmd/flutter_adblocker_webview/issues
version: 1.2.1-beta
homepage: https://github.com/islamdidarmd/flutter_adblocker_webview

environment:
  sdk: ^3.6.0

workspace:
  - packages/adblocker_core

dependencies:
  adblocker_core:
    path: packages/adblocker_core
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
