name: adblocker_webview
description: A webview for flutter with adblocking capability. It's currently based on Flutter InAppWebview Plugin.
repository: https://github.com/islamdidarmd/flutter_adblocker_webview
issue_tracker: https://github.com/islamdidarmd/flutter_adblocker_webview/issues
version: 1.1.1
homepage: https://github.com/islamdidarmd/flutter_adblocker_webview

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.5'

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.1
  flutter_inappwebview: ^5.8.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
