name: adblocker_core_example
description: "Demonstrates how to use the adblocker_core plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  adblocker_core:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
  - assets/easy_privacy_lite.txt
  - assets/adguard_base.txt
  - assets/adguard_annyoance.txt
