name: adblocker_manager
description: "Manager package for handling multiple ad-blocking filters"
version: 0.0.1
homepage: "none"

environment:
  sdk: ^3.7.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  adblocker_core:
    path: ../adblocker_core
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/adguard_base.txt
    - assets/easylist.txt
