name: adblocker_manager
description: "Manager package for handling multiple ad-blocking filters"
version: 1.0.0
homepage: "none"

environment:
  sdk: ^3.7.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  adblocker_core: ^0.1.0
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/adguard_base.txt
    - assets/easylist.txt
