name: adblocker_core
description: "Core plugin for adblocker weview"
version: 0.0.1
homepage: 'none'

environment:
  sdk: ^3.5.3
  flutter: ^3.24.3

dependencies:
  ffi: ^2.1.3
  ffigen: ^15.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.islamdidarmd.adblocker_core
        pluginClass: AdblockerCorePlugin
      ios:
        pluginClass: AdblockerCorePlugin

  assets:
    - assets/easylist.txt