name: adblocker_core
description: "Core package for adblocker webview"
version: 0.1.0
homepage: "https://github.com/islamdidarmd/flutter_adblocker_webview"

environment:
  sdk: ^3.7.0
  flutter: '>=3.29.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter


